---

- name: Vhost | Include HTTPD configuration
  import_tasks: httpd.yml
  when:
    - webService == "httpd" or httpdRoleName in role_names
    - Users is defined

- name: Vhost | Include NGINX configuration
  import_tasks: nginx.yml
  when:
    - webService == "nginx" or nginxRoleName in role_names
    - Users is defined
