---

- name: Link custom folder inside template folder
  file:
    src: "{{ nginxVhostLocation }}"
    dest: "{{ role_path }}/templates/nginx/custom"
    state: link
  delegate_to: localhost
  when: nginxVhostCustom

- name: Setting up Folders
  file:
    path: "/etc/nginx/{{ item }}"
    state: "directory"
  with_items:
    - sites-available
    - sites-enabled

- name: Setting up log folder users
  file:
    path: "/home/{{ item.name }}/logs"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    state: "directory"
  with_items:
    - "{{ Users }}"
  loop_control:
    label: "Creating logs folder: /home/{{ item.name }}/logs"

- name: Installing vhost
  template:
    src: "{{ nginx_vhost }}"
    dest: /etc/nginx/sites-available/{{ item.1.name }}.conf
  with_subelements:
    - "{{ Users }}"
    - "Domains"
  notify: restart nginx
  loop_control:
    label: "Creating vhost for: {{ item.1.name }} inside: /etc/nginx/sites-available/"

- name: Placing symbolic link
  file:
    src: /etc/nginx/sites-available/{{ item.1.name }}.conf
    state: link
    dest: /etc/nginx/sites-enabled/{{ item.1.name }}.conf
  with_subelements:
    - "{{ Users }}"
    - "Domains"
  loop_control:
    label: "Linking: /etc/nginx/sites-available/{{ item.1.name }}.conf To: /etc/nginx/sites-enabled/{{ item.1.name }}.conf"

- name: Place include in the nginx conf file
  lineinfile:
    path: "/etc/nginx/nginx.conf"
    state: present
    insertafter: "http {"
    line: "include /etc/nginx/sites-enabled/*.conf;"
