---

- name: Setting up Folders
  file:
    path: "/etc/nginx/{{ item }}"
    state: "directory"
  with_items:
    - sites-available
    - sites-enabled

- name: Installing vhost
  template:
    src: "{{ nginx_vhost }}"
    dest: /etc/nginx/sites-available/{{ item.1.name }}.conf
  with_subelements:
    - "{{ Users }}"
    - "Domains"
  notify: restart nginx

- name: Placing symbolic link
  file:
    src: /etc/nginx/sites-available/{{ item.1.name }}.conf
    state: link
    dest: /etc/nginx/sites-enabled/{{ item.1.name }}.conf
  with_subelements:
    - "{{ Users }}"
    - "Domains"

- name: Place include in the nginx conf file
  lineinfile:
    path: "/etc/nginx/nginx.conf"
    state: present
    insertafter: "http {"
    line: "include /etc/nginx/sites-enabled/*.conf;"
